{% set version = '0.4.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-deps
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/deps_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/deps/deps_{{ version }}.tar.gz
  sha256: d0bc90d1a17d315c9f9abdaa5beefdd4581ca626a651fb8df40ad9155b5af490

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-jsonlite
    - r-remotes
    - r-renv
  run:
    - r-base
    - r-jsonlite
    - r-remotes
    - r-renv

test:
  commands:
    - $R -e "library('deps')"           # [not win]
    - "\"%R%\" -e \"library('deps')\""  # [win]

about:
  home: https://hub.analythium.io/deps/, https://github.com/analythium/deps
  license: MIT
  summary: Manage your source code dependencies by decorating your existing R code with special,
    'roxygen'-style comments.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: deps
# Type: Package
# Title: Dependency Management with 'roxygen'-Style Comments
# Version: 0.4.0
# Authors@R: c( person(given = "Peter", family = "Solymos", comment = c(ORCID = "0000-0001-7337-1740"), role = c("aut", "cre"), email = "peter@analythium.io"), person(given = "Analythium Solutions Inc.", role = c("cph", "fnd")))
# Description: Manage your source code dependencies by decorating your existing R code with special, 'roxygen'-style comments.
# License: MIT + file LICENSE
# LazyLoad: yes
# Imports: renv, jsonlite, remotes
# RoxygenNote: 7.3.1
# Encoding: UTF-8
# BugReports: https://github.com/analythium/deps/issues
# URL: https://hub.analythium.io/deps/, https://github.com/analythium/deps
# Language: en-US
# NeedsCompilation: no
# Packaged: 2024-07-07 14:44:32 UTC; Peter
# Author: Peter Solymos [aut, cre] (<https://orcid.org/0000-0001-7337-1740>), Analythium Solutions Inc. [cph, fnd]
# Maintainer: Peter Solymos <peter@analythium.io>
# Repository: CRAN
# Date/Publication: 2024-07-07 15:00:02 UTC
